"""Edit Invoice model: add pay_id field, edit name of type field to method

Revision ID: b36d42bb4fef
Revises: 1fadf32db11a
Create Date: 2025-01-05 00:51:12.904324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36d42bb4fef'
down_revision: Union[str, None] = '1fadf32db11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_id', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('method', sa.String(length=32), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_column('method')
        batch_op.drop_column('pay_id')

    # ### end Alembic commands ###
